import { defineStore } from "pinia";

export const useUserStore = defineStore("UserData", {
  state: () => ({
    small: "hii",
    list: [
      {
        id: 1,
        Company: "Apple",
        Stage: "Not Applied",
        Position: "Staff Product Manager",
        Deadline: "2025-01-13",
        InterviewDate: "",
        Url: "linkedin.com/job",
        Referral: "Referred!",
        Resumelink: "Resume Templdawdawdawdawdate",
      },
      {
        id: 2,
        Company: "Google",
        Stage: "Applied",
        Position: "Senior Product Madawdawdawdawdawager",
        Deadline: "2025-01-07",
        InterviewDate: "2025-01-15",
        Url: "linkedin.com/job",
        Referral: "No",
        Resumelink: "Resume Template",
      },
      {
        id: 3,
        Company: "Cisco",
        Stage: "Interview",
        Position: "Senior Product Manager",
        Deadline: "2025-01-13",
        InterviewDate: "2025-01-17",
        Url: "linkedin.com/job",
        Referral: "Referred!",
        Resumelink: "Resume Template",
      },
      {
        id: 4,
        Company: "Netflix",
        Stage: "Rejected",
        Position: "Senior Product Manager",
        Deadline: "2025-01-13",
        InterviewDate: "",
        Url: "linkedin.com/job",
        Referral: "Referred!",
        Resumelink: "Resume Template",
      },
      {
        id: 5,
        Company: "Microsoft",
        Stage: "Rejected",
        Position: "Product Manager",
        Deadline: "2025-01-09",
        InterviewDate: "2025-01-11",
        Url: "linkedin.com/job",
        Referral: "No",
        Resumelink: "Resume Template",
      },
      {
        id: 6,
        Company: "Datadog",
        Stage: "Offered",
        Position: "Staff Product Manager",
        Deadline: "2025-01-05",
        InterviewDate: "",
        Url: "linkedin.com/job",
        Referral: "Referred!",
        Resumelink: "Resume Template",
      },
      {
        id: 7,
        Company: "Samsara",
        Stage: "Interview",
        Position: "Product Manager",
        Deadline: "2025-01-04",
        InterviewDate: "",
        Url: "linkedin.com/job",
        Referral: "No",
        Resumelink: "Resume Template",
      },
      {
        id: 8,
        Company: "Databricks",
        Stage: "Waiting for a referral",
        Position: "Senior Product Manager",
        Deadline: "2025-01-07",
        InterviewDate: "",
        Url: "linkedin.com/job",
        Referral: "No",
        Resumelink: "Resume Template",
      },
      {
        id: 9,
        Company: "HP",
        Stage: "Rejected",
        Position: "Senior Product Manager",
        Deadline: "2025-01-06",
        InterviewDate: "2025-01-16",
        Url: "linkedin.com/job",
        Referral: "Referred!",
        Resumelink: "Resume Template",
      },
      {
        id: 10,
        Company: "Meta",
        Stage: "Applied",
        Position: "Senior Product Manager",
        Deadline: "2025-01-13",
        InterviewDate: "",
        Url: "linkedin.com/job",
        Referral: "Referred!",
        Resumelink: "Resume Template",
      },
      {
        id: 11,
        Company: "Blind",
        Stage: "Rejected",
        Position: "Senior Product Manager",
        Deadline: "2025-01-13",
        InterviewDate: "",
        Url: "linkedin.com/job",
        Referral: "Referred!",
        Resumelink: "Resume Template",
      },
      {
        id: 12,
        Company: "Reddit",
        Stage: "Applied",
        Position: "Senior Product Manager",
        Deadline: "2025-01-13",
        InterviewDate: "2025-01-11",
        Url: "linkedin.com/job",
        Referral: "No",
        Resumelink: "Resume Template",
      },
      {
        id: 13,
        Company: "AWS",
        Stage: "Rejected",
        Position: "Staff Product Manager",
        Deadline: "2025-01-13",
        InterviewDate: "",
        Url: "linkedin.com/job",
        Referral: "Referred!",
        Resumelink: "Resume Template",
      },
      {
        id: 14,
        Company: "Snowflake",
        Stage: "Rejected",
        Position: "Principal Product Manager",
        Deadline: "2025-01-13",
        InterviewDate: "",
        Url: "linkedin.com/job",
        Referral: "Referred!",
        Resumelink: "Resume Template",
      },
      {
        id: 15,
        Company: "TikTok",
        Stage: "Applied",
        Position: "Senior Product Manager",
        Deadline: "2025-01-13",
        InterviewDate: "",
        Url: "linkedin.com/job",
        Referral: "No",
        Resumelink: "Resume Template",
      },
      {
        id: 16,
        Company: "Snap",
        Stage: "Waiting for a referral",
        Position: "Senior Product Manager",
        Deadline: "2025-01-13",
        InterviewDate: "",
        Url: "linkedin.com/job",
        Referral: "Referred!",
        Resumelink: "Resume Template",
      },
      {
        id: 17,
        Company: "Block",
        Stage: "Rejected",
        Position: "Senior Product Manager",
        Deadline: "2025-01-13",
        InterviewDate: "",
        Url: "linkedin.com/job",
        Referral: "Referred!",
        Resumelink: "Resume Template",
      },
    ],
    profile: {
      name: "John Doe",
      email: "john.doe@example.com",
      profileImageUrl: "/public/image.png",
      about:
        "I am a software developer with a passion for building modern web applications and working with frontend frameworks like Vue.js.",
      dashboard: {
        info: "Some quick stats or user-related info",
        chart1: "Data for circle graph (e.g. skill distribution)",
        chart2: "Data for bar graph (e.g. project contributions over time)",
      },
      editable: true,
    },
  }),
  getters: {
    getlist: (state) => state.list,
  },
  actions: {
    replace(updated, original) {
      const index = this.list.findIndex((item) => item == original);
      if (index !== -1) {
        this.list[index] = { ...updated };
      }
    },
    del(val) {
      this.list = this.list.filter((app) => {
        return !(app.Company === val.Company && app.Position === val.Position);
      });
    },
  },
});
